version: '3.8'

services:
  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: iam-generator-backend
    restart: unless-stopped
    environment:
      - PORT=8000
      - PYTHONPATH=/app/src
      - LOG_LEVEL=info
    ports:
      - "8000:8000"
    volumes:
      # Mount for persistent data and logs
      - ./data:/app/data
      - ./logs:/app/logs
      # Optional: Mount AWS credentials (for local development)
      # - ~/.aws:/home/appuser/.aws:ro
    networks:
      - iam-generator-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: production
    container_name: iam-generator-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - iam-generator-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  iam-generator-network:
    driver: bridge
    name: iam-generator-network

volumes:
  # Named volumes for data persistence
  iam-data:
    name: iam-generator-data
  iam-logs:
    name: iam-generator-logs
